export const LLM_STAGE_KEYS = [
  'kernelIdeator',
  'kernelEvaluator',
  'kernelEvolver',
  'conceptSeeder',
  'conceptEvolverSeeder',
  'conceptArchitect',
  'conceptEngineer',
  'conceptEvaluator',
  'conceptStressTester',
  'conceptSpecificity',
  'conceptScenario',
  'spine',
  'entityDecomposer',
  'characterDecomposer',
  'characterContextualizer',
  'worldbuildingDecomposer',
  'structure',
  'planner',
  'accountant',
  'lorekeeper',
  'writer',
  'choiceGenerator',
  'structureEvaluator',
  'promiseTracker',
  'proseQuality',
  'npcIntelligence',
  'agendaResolver',
  'sceneIdeator',
  'structureRewrite',
  'spineRewrite',
  'contentOneShot',
  'contentTasteDistiller',
  'contentSparkstormer',
  'contentPacketer',
  'contentEvaluator',
  'characterWeb',
  'charKernel',
  'charTridimensional',
  'charAgency',
  'charRelationships',
  'charPresentation',
  'worldbuildingSeed',
  'worldbuildingElaboration',
] as const;

export type LlmStage = (typeof LLM_STAGE_KEYS)[number];
