export const LLM_STAGE_KEYS = [
  'kernelIdeator',
  'kernelEvaluator',
  'kernelEvolver',
  'conceptIdeator',
  'conceptEvolver',
  'conceptEvaluator',
  'conceptStressTester',
  'conceptSpecificity',
  'conceptScenario',
  'spine',
  'entityDecomposer',
  'structure',
  'planner',
  'accountant',
  'lorekeeper',
  'writer',
  'structureEvaluator',
  'promiseTracker',
  'proseQuality',
  'npcIntelligence',
  'agendaResolver',
  'sceneIdeator',
] as const;

export type LlmStage = (typeof LLM_STAGE_KEYS)[number];
