export const LLM_STAGE_KEYS = [
  'kernelIdeator',
  'kernelEvaluator',
  'kernelEvolver',
  'conceptSeeder',
  'conceptEvolverSeeder',
  'conceptArchitect',
  'conceptEngineer',
  'conceptEvaluator',
  'conceptStressTester',
  'conceptSpecificity',
  'conceptScenario',
  'spine',
  'entityDecomposer',
  'structure',
  'planner',
  'accountant',
  'lorekeeper',
  'writer',
  'structureEvaluator',
  'promiseTracker',
  'proseQuality',
  'npcIntelligence',
  'agendaResolver',
  'sceneIdeator',
  'structureRewrite',
  'spineRewrite',
] as const;

export type LlmStage = (typeof LLM_STAGE_KEYS)[number];
