export const THREAD_PACING = {
  HIGH_URGENCY_OVERDUE_PAGES: 4,
  MEDIUM_URGENCY_OVERDUE_PAGES: 7,
  LOW_URGENCY_OVERDUE_PAGES: 10,
  PROMISE_AGING_NOTICE_PAGES: 5,
  PROMISE_SCOPE_EXPIRY: {
    SCENE: 4,
    BEAT: null,
    ACT: null,
    STORY: null,
  },
  MAX_ACTIVE_PROMISES: 8,
} as const;
