export const THREAD_PACING = {
  HIGH_URGENCY_OVERDUE_PAGES: 4,
  MEDIUM_URGENCY_OVERDUE_PAGES: 7,
  LOW_URGENCY_OVERDUE_PAGES: 10,
  MAX_INHERITED_PROMISES: 5,
  PROMISE_AGE_OUT_PAGES: 10,
} as const;
