/**
 * Scene direction option and selection types.
 *
 * A SceneDirectionOption is generated by the scene ideator LLM stage.
 * A SelectedSceneDirection is what the user confirms (with possible free-text edits).
 */

import type { ScenePurpose, ValuePolarityShift, PacingMode } from './scene-direction-taxonomy.js';

export interface SceneDirectionOption {
  readonly scenePurpose: ScenePurpose;
  readonly valuePolarityShift: ValuePolarityShift;
  readonly pacingMode: PacingMode;
  readonly sceneDirection: string;
  readonly dramaticJustification: string;
}

export interface SelectedSceneDirection {
  readonly scenePurpose: ScenePurpose;
  readonly valuePolarityShift: ValuePolarityShift;
  readonly pacingMode: PacingMode;
  readonly sceneDirection: string;
  readonly dramaticJustification: string;
}
